name       : visidata
version    : 2.11.1
release    : 8
source     :
    - https://github.com/saulpw/visidata/archive/refs/tags/v2.11.1.tar.gz : 8d4f3f7453c1914a40eb00edc4196db0b88819d9d4d1ae3a22f603f8b7d5126d
homepage   : https://www.visidata.org/
license    : GPL-3.0-only
component  : office.viewers
summary    : A terminal spreadsheet multitool for discovering and arranging data
description: |
    VisiData supports tsv, csv, sqlite, json, xlsx (Excel), hdf5, and many other formats.
build      : |
    %python3_setup
install    : |
    %python3_install
