name       : visidata
version    : '2.10'
release    : 4
source     :
    - https://github.com/saulpw/visidata/archive/refs/tags/v2.10.tar.gz : 7b14c8db93bc502c6b2628ab195e028370ab42ed60c2ab2939e65fe4d427377b
homepage   : https://www.visidata.org/
license    : GPL-3.0-only
component  : office.viewers
summary    : A terminal spreadsheet multitool for discovering and arranging data
description: |
    VisiData supports tsv, csv, sqlite, json, xlsx (Excel), hdf5, and many other formats.
build      : |
    %python3_setup
install    : |
    %python3_install
