name       : visidata
version    : 2.10.2
release    : 6
source     :
    - https://github.com/saulpw/visidata/archive/refs/tags/v2.10.2.tar.gz : a53d77ef1c3981239855df672cdba6c8431d2d0361195acfeb5e2d8f8e980662
homepage   : https://www.visidata.org/
license    : GPL-3.0-only
component  : office.viewers
summary    : A terminal spreadsheet multitool for discovering and arranging data
description: |
    VisiData supports tsv, csv, sqlite, json, xlsx (Excel), hdf5, and many other formats.
build      : |
    %python3_setup
install    : |
    %python3_install
