name       : visidata
version    : 2.8
release    : 1
source     :
    - https://github.com/saulpw/visidata/archive/refs/tags/v2.8.tar.gz : 1b28a2b5d0a1eaa9478be86941ecdb9c5aa06490d1d95d016fb63cfd9a76e739
license    : GPL-3.0-only
component  : office.viewers
summary    : A terminal spreadsheet multitool for discovering and arranging data 
description: |
    VisiData supports tsv, csv, sqlite, json, xlsx (Excel), hdf5, and many other formats.
build      : |
    %python3_setup
install    : |
    %python3_install
