name       : visidata
version    : 2.10.1
release    : 5
source     :
    - https://github.com/saulpw/visidata/archive/refs/tags/v2.10.1.tar.gz : a26b9773ef6cf249dad401a207f3a560ba29d1e084d9707607061d96dbd3f1f2
homepage   : https://www.visidata.org/
license    : GPL-3.0-only
component  : office.viewers
summary    : A terminal spreadsheet multitool for discovering and arranging data
description: |
    VisiData supports tsv, csv, sqlite, json, xlsx (Excel), hdf5, and many other formats.
build      : |
    %python3_setup
install    : |
    %python3_install
